# Example league settings with DST and Kicker scoring configuration
# Copy this file and modify for your league's specific scoring system

# Number of teams in the league
teams: 12

# Roster positions and starting requirements
roster:
  QB: 1      # 1 starting QB
  RB: 2      # 2 starting RBs  
  WR: 2      # 2 starting WRs
  TE: 1      # 1 starting TE
  FLEX: 1    # 1 FLEX (RB/WR/TE)
  K: 1       # 1 starting Kicker
  DEF: 1     # 1 starting Defense/Special Teams

# Which positions are eligible for FLEX
flex_positions: ["RB", "WR", "TE"]

# Scoring system
scoring:
  # Passing (for QBs)
  passYdsPerPt: 25        # 1 point per 25 passing yards
  passTd: 4               # 4 points per passing TD
  int: -2                 # -2 points per interception thrown
  pickSixThrown: 0        # Additional penalty for pick-6 (rare in data)
  sackTaken: 0            # Penalty for sacks taken (rare in data)
  
  # Rushing (for all positions)
  rushYdsPerPt: 10        # 1 point per 10 rushing yards
  rushTd: 6               # 6 points per rushing TD
  
  # Receiving (for all positions)
  rec: 1                  # 1 point per reception (PPR)
  recYdsPerPt: 10         # 1 point per 10 receiving yards
  recTd: 6                # 6 points per receiving TD
  
  # Miscellaneous
  twoPt: 2                # 2 points per 2-point conversion
  fumLost: -2             # -2 points per fumble lost
  
  # DST/Defense Scoring
  dstSack: 1              # 1 point per sack
  dstInt: 2               # 2 points per interception
  dstFumbleRecovery: 2    # 2 points per fumble recovery
  dstDefensiveTd: 6       # 6 points per defensive/special teams TD
  dstSafety: 2            # 2 points per safety
  dstBlockedKick: 2       # 2 points per blocked kick
  
  # Points Allowed (tiered scoring)
  dstPointsAllowed0: 10        # 10 points for shutout (0 points allowed)
  dstPointsAllowed1_6: 7       # 7 points for 1-6 points allowed
  dstPointsAllowed7_13: 4      # 4 points for 7-13 points allowed
  dstPointsAllowed14_20: 1     # 1 point for 14-20 points allowed
  dstPointsAllowed21_27: 0     # 0 points for 21-27 points allowed
  dstPointsAllowed28_34: -1    # -1 point for 28-34 points allowed
  dstPointsAllowed35Plus: -4   # -4 points for 35+ points allowed
  
  # Kicker Scoring (distance-based field goals)
  kFg0_39: 3              # 3 points for field goals 0-39 yards
  kFg40_49: 4             # 4 points for field goals 40-49 yards
  kFg50Plus: 5            # 5 points for field goals 50+ yards
  kXp: 1                  # 1 point per extra point made
  kFgMiss: 0              # Penalty for missed field goals (usually 0)
  kXpMiss: 0              # Penalty for missed extra points (usually 0)
